### ISSUE TITLE
Bug / Property 'PORSCHE_DESIGN_SYSTEM_CDN' is declared two times

### ISSUE THREAD

**Issue by niklaskappler** [porscheui/porsche-design-system-contribution#52] opened 2021-04-20 06:39 UTC
**Description**
Version 2.0.1 of @porsche-design-system/components-angular seems to introduce an issue which leads to breaking builds while using the package in combination with the @porsche-design-system/utilities package (happend with latest version 4.0.0). It seems this behaviour was introduced with version 2.0.1.In both packages you declare the variable PORSCHE_DESIGN_SYSTEM_CDN in the global namespace, which the typescript compile doesn't like.

**To Reproduce**  
1. Use the sample-integration-angular repo
2. Update @porsche-design-system/components-angular to 2.0.1
3. Install dependencies & run a prod build with "ng build --prod"
4. Compilation will stop with following errors:
"error TS2733: Property 'PORSCHE_DESIGN_SYSTEM_CDN' was also declared here." and
"error TS2718: Duplicate property 'PORSCHE_DESIGN_SYSTEM_CDN'."

**Expected behavior**  
Webpack bundling does not fail with an error due to duplicate identifier

**Screenshots**  
![Bildschirmfoto 2021-04-20 um 08 33 04](https://user-images.githubusercontent.com/19165207/115348573-10529e80-a1b3-11eb-8681-05edb2ea9ef5.png)

**Test Device (please complete the following information):**  
 - Device: desktop
 - OS: MacOS

**Comment by niklaskappler** [comment] 2021-04-20 06:41
Latest known working combination "@porsche-design-system/components-angular": "^2.0.0-rc.10" and "@porsche-design-system/utilities": "^4.0.0",

**Comment by SetupCoding** [comment] 2021-04-20 15:51
Hey @niklaskappler thanks for your report!
The issue is fixed in the latest `2.0.1-beta.0` release.

**Closed** 2021-04-21 06:42 UTC
Labels: bug 🛑
